# Generated by Django 3.0.7 on 2020-07-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200725_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('to read', 'to read'), ('reading', 'reading'), ('read', 'read')], default='to read', max_length=25),
        ),
    ]
