# Generated by Django 3.0.7 on 2020-07-25 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200725_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='ownder',
            new_name='owner',
        ),
    ]
