# Generated by Django 3.0.7 on 2020-07-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200725_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('to-read', 'to-read'), ('reading', 'reading'), ('read', 'read')], default='to read', max_length=25),
        ),
    ]
