# Generated by Django 3.0.7 on 2020-07-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200727_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_timeline',
            field=models.BooleanField(default=True),
        ),
    ]
